apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sync-service-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sync-service
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: sync-service
  apiGroup: rbac.authorization.k8s.io

