apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-helm-operator-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | first }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
