apiVersion: v1
kind: Service
metadata:
  name: neo4j-operator
  namespace: neo4j
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: bolt
      port: 7474
      targetPort: 7474
  selector:
    app: neo4j-operator-service
  type: ClusterIP
