apiVersion: v1
kind: Service
metadata:
  name: sync-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: sync-service
  type: ClusterIP
