apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: neo4j
  ports:
{{- range .Values.service.ports }}
  - protocol: TCP
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
{{- end }}
